[package]
name = "ascii-fixer"
version = "1.0.2"
edition = "2024"

[dependencies]
iced = { version = "0.14.0", features = ["advanced", "image"] }
open = "5.3.3"
rfd = "0.17.2"

[build-dependencies]
winresource = "0.1.29"
